Check order
PUArallelepiped/PUN-street-Universal-Access pull request #102
Opened 2023-12-20 14:27 UTC by nonorze-VOXX

2023-12-21 03:41 UTC, wj461 requested changes
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/6f070f33-44fe-4e57-82fc-455a696ff373)
Check order按鈕會在status是5的時後 才出現

2023-12-21 13:49 UTC, nonorze-VOXX commented
> ![圖片](https://private-user-images.githubusercontent.com/119517466/292079576-6f070f33-44fe-4e57-82fc-455a696ff373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjQ2MTUsIm5iZiI6MTcwMzE2NDMxNSwicGF0aCI6Ii8xMTk1MTc0NjYvMjkyMDc5NTc2LTZmMDcwZjMzLTQ0ZmUtNGU1Ny04MmZjLTQ1NWE2OTZmZjM3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMzExNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzVmYmViNWE1NDcyYzYwZTYyNmI3ODEzNmMwNTAzNTg1OGFlN2FiNjUzM2Q0MjM2NzE0NDllNDNmMmY3YjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4V7exQRlj0Y2ooyzsOloTkotMqcHGge33zJqA3v48y4) Check order按鈕會在status是5的時後 才出現

fixed

2023-12-22 08:57 UTC, wj461 commented on db/i50-order.sql
> -    (1, 1, 2, 1, 1, 6, 100, '2020-01-01 00:04:00', '台北市', 1),
why you change db data?

2023-12-22 16:58 UTC, wj461 approved these changes
looks good

2023-12-22 17:07 UTC, merged