Conn history
PUArallelepiped/PUN-street-Universal-Access pull request #103
Opened 2023-12-20 15:03 UTC by nonorze-VOXX

2023-12-21 02:55 UTC, wj461 requested changes

2023-12-21 02:55 UTC, wj461 commented on frontend/src/lib/components/PUA/historyCard.svelte
> +			fetch(backendPath + '/store/1/rate', {
我覺得你這邊的store_id 可以直接用get_history回傳的store_id
不用固定1

2023-12-21 13:39 UTC, nonorze-VOXX commented on frontend/src/lib/components/PUA/historyCard.svelte
> +			fetch(backendPath + '/store/1/rate', {
fixed

2023-12-22 08:59 UTC, wj461 approved these changes
looks good

2023-12-22 17:18 UTC, merged