item page connect backend
PUArallelepiped/PUN-street-Universal-Access pull request #105
Opened 2023-12-21 02:23 UTC by OuChiaYun

2023-12-21 04:01 UTC, wj461 requested changes
按下Add cart後 可以跳轉回到store page

2023-12-21 14:37 UTC, nonorze-VOXX approved these changes, later dismissed
LGTM

2023-12-21 14:38 UTC, nonorze-VOXX commented
conflict

2023-12-21 20:15 UTC, OuChiaYun commented
> 按下Add cart後 可以跳轉回到store page

fixed,還是應該在原頁面跳提示說加入成功就好?

2023-12-21 20:15 UTC, OuChiaYun commented
> conflict

fixed

2023-12-22 16:30 UTC, wj461 approved these changes
looks good

2023-12-22 17:16 UTC, nonorze-VOXX approved these changes
LGTM

2023-12-22 17:17 UTC, merged