store page seller connect addItem , backend
PUArallelepiped/PUN-street-Universal-Access pull request #107
Opened 2023-12-21 19:39 UTC by OuChiaYun

http://localhost:5173/shops/2/store_page_seller
兩頁都有接上去了，應該可以正常運作，包括新增product

2023-12-22 09:21 UTC, wj461 requested changes
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/1326252c-1453-4960-a16d-3626562271c5)
我新增完一個shipping_discount之後
馬上按下刪除的時候 給後端的discount_id 會是0
所以刪不到

2023-12-22 13:20 UTC, OuChiaYun commented
> ![圖片](https://private-user-images.githubusercontent.com/119517466/292451483-1326252c-1453-4960-a16d-3626562271c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTE1MTcsIm5iZiI6MTcwMzI1MTIxNywicGF0aCI6Ii8xMTk1MTc0NjYvMjkyNDUxNDgzLTEzMjYyNTJjLTE0NTMtNDk2MC1hMTZkLTM2MjY1NjIyNzFjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQxMzIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzA2N2I0N2VjODAwNmM0NTVmN2JhMGZhNTAyNzg3NTg2MmY3OTlhOWJkMzY3MzM1OGJiYTIwNjFmYWY0NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.83D5F8woVcNsxgpPn_iZ3Cc2H9-HUVdy-gcAUzTrWnk) 我新增完一個shipping_discount之後 馬上按下刪除的時候 給後端的discount_id 會是0 所以刪不到

fixed

2023-12-22 17:19 UTC, wj461 requested changes
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/334b93d4-36bc-446d-8d1c-d8fbc25b0288)
這裡應該可以拿url的store_id去post shipping_discount嗎？
像是新增category的時候也會使用當前store的id那樣
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/a8efb1bf-3a1c-4053-a9f7-523604fe34bd)

2023-12-22 17:34 UTC, nonorze-VOXX requested changes
編輯商品頁面的商品敘述會消失

2023-12-22 17:37 UTC, nonorze-VOXX commented on frontend/src/routes/shops/[shop]/store_page_seller/+page.svelte
> +				></TagLabelArea>
when no tag can choose, + will appear, but it cant work

2023-12-22 17:41 UTC, OuChiaYun commented on frontend/src/routes/shops/[shop]/store_page_seller/+page.svelte
> +				></TagLabelArea>
這邊的話，把前面的標籤刪掉後可選的標籤就會出現在剛剛沒有東西顯示的menu裡面
要改成無標籤可選時就不顯+嗎?

2023-12-22 20:25 UTC, wj461 submitted a review, later dismissed
looks good

2023-12-22 21:28 UTC, wj461 approved these changes, later dismissed
looks good

2023-12-24 06:28 UTC, nonorze-VOXX approved these changes
LGTM

2023-12-24 06:28 UTC, merged