updateOrderStatus connect backend
PUArallelepiped/PUN-street-Universal-Access pull request #109
Opened 2023-12-23 11:58 UTC by OuChiaYun

http://localhost:5173/order/updateOrderStatus

預設shop id=1

2023-12-24 06:30 UTC, nonorze-VOXX commented
conflict

2023-12-24 06:31 UTC, nonorze-VOXX commented
yo bro your goto look go wrong page

2023-12-25 13:33 UTC, OuChiaYun commented
> conflict

 fixed

2023-12-25 13:34 UTC, OuChiaYun commented
> yo bro your goto look go wrong page

目前先 ./，等history page 結束再改

2023-12-25 15:44 UTC, nonorze-VOXX requested changes

2023-12-25 15:44 UTC, nonorze-VOXX commented on frontend/src/lib/components/PUA/orderStatusCard.svelte
> +		>
press button will trigger it

2023-12-25 15:44 UTC, nonorze-VOXX commented on frontend/src/routes/order/updateOrderStatus/+page.svelte
> +	}
use invalidateAll to refresh page

2023-12-25 16:43 UTC, OuChiaYun commented on frontend/src/lib/components/PUA/orderStatusCard.svelte
> +		>
fixed

2023-12-25 16:43 UTC, OuChiaYun commented on frontend/src/routes/order/updateOrderStatus/+page.svelte
> +	}
fixed

2023-12-26 05:18 UTC, nonorze-VOXX requested changes

2023-12-26 05:18 UTC, nonorze-VOXX commented on frontend/src/lib/components/PUA/orderStatusCard.svelte
>  		</button>
之前不是說按鈕在按鈕裡面會有問題嗎

2023-12-26 05:45 UTC, OuChiaYun commented on frontend/src/lib/components/PUA/orderStatusCard.svelte
>  		</button>
不是 是按鈕疊在按鈕上面，中間有div 隔著好像會有問題

2023-12-26 12:09 UTC, nonorze-VOXX approved these changes
LGTM

2023-12-26 12:09 UTC, merged