page connect finish
PUArallelepiped/PUN-street-Universal-Access pull request #117
Opened 2023-12-28 05:38 UTC by OuChiaYun

profile -> go to store、process order、change and save button rm
admin -> history detail, fixed bg white bug
store and user profile look different

2023-12-28 14:58 UTC, huhuhu0420 commented on frontend/src/lib/navbar.svelte
remove changes

2023-12-28 16:11 UTC, OuChiaYun commented on frontend/src/lib/navbar.svelte
fiexd

2023-12-28 16:36 UTC, nonorze-VOXX requested changes

2023-12-28 16:36 UTC, nonorze-VOXX commented on frontend/src/lib/components/PUA/store_page_seller/storeProductCard.svelte
> +	class="flex items-center justify-between overflow-hidden rounded-3xl bg-white duration-150 hover:scale-[1.02]"
![image](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/93046487/0fecf92e-0210-47e5-a2e6-a8f9f1bf0a13)
there have some bug

2023-12-28 16:36 UTC, nonorze-VOXX commented on frontend/src/routes/admin/+page.svelte
> +			</div>
![image](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/93046487/284a3f04-2314-4eb4-a5c3-355960a07ef5)

2023-12-29 18:55 UTC, OuChiaYun commented on frontend/src/routes/admin/+page.svelte
> +			</div>
fixed
我讓他超過時換行

2023-12-29 18:55 UTC, OuChiaYun commented on frontend/src/lib/components/PUA/store_page_seller/storeProductCard.svelte
> +	class="flex items-center justify-between overflow-hidden rounded-3xl bg-white duration-150 hover:scale-[1.02]"
fixed,改計算方式

2023-12-30 08:09 UTC, wj461 reviewed
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/3a772d63-14be-46a4-b782-b1b9439a93ac)
這個或許可以讓他換行嗎？

2024-01-02 06:59 UTC, OuChiaYun commented
> ![圖片](https://private-user-images.githubusercontent.com/119517466/293450088-3a772d63-14be-46a4-b782-b1b9439a93ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzczMjksIm5iZiI6MTcwNDE3NzAyOSwicGF0aCI6Ii8xMTk1MTc0NjYvMjkzNDUwMDg4LTNhNzcyZDYzLTE0YmUtNDZhNC1iNzgyLWIxYjk0MzlhOTNhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwNjMwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjU2NjRhNDA4NTk2MDcxMjI3NzM3NTkwYmEzNGNhNjkzYTk5OTA0YzE0ZjFhOTM3NzhkMzU5Y2FjYmQ2Njg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_xzWuYj8XsE6xa-0ErKKZctIg4oMBQE-TJA-pgsQm8) 這個或許可以讓他換行嗎？

fixed,這個我不太知道怎麼解決，所以我讓她文本超過兩行時換行

2024-01-05 10:53 UTC, nonorze-VOXX submitted a review, later dismissed
LGTM

2024-01-05 19:22 UTC, nonorze-VOXX approved these changes
LGTM

2024-01-05 19:22 UTC, merged