add user table
PUArallelepiped/PUN-street-Universal-Access pull request #14
Opened 2023-10-11 06:17 UTC by glu8637

2023-10-11 08:17 UTC, nonorze-VOXX requested changes
user is not allow

2023-10-11 08:17 UTC, nonorze-VOXX commented on User_table.txt
> +CREATE TABLE User(
it is no work

2023-10-11 08:27 UTC, glu8637 commented on User_table.txt
> +CREATE TABLE User(
try now

2023-10-12 01:52 UTC, nonorze-VOXX requested changes

2023-10-12 01:52 UTC, nonorze-VOXX commented on User_table.txt
> +  Authority int not null
these three is not in srs
why add these

2023-10-12 01:52 UTC, nonorze-VOXX commented on User_table.txt
> +  Address char[64] not null,
sql language should Uppercase

2023-10-12 02:54 UTC, nonorze-VOXX commented on User_table.txt
> +  Authority int not null
update: it is for someone want collect people private information

2023-10-12 14:32 UTC, orangeOAO approved these changes

2023-10-16 17:29 UTC, nonorze-VOXX requested changes
new request: put in db folder and sub filename request .sql

2023-10-17 15:51 UTC, wj461 commented on User_table.txt
> +  ID int unique not null,
I think you can use serial replace int

2023-10-17 15:52 UTC, wj461 commented on User_table.txt
> +  Name char[32] not null,
I think char[32] can use VARCHAR(32)

2023-10-18 08:02 UTC, orangeOAO approved these changes

2023-10-18 08:13 UTC, orangeOAO approved these changes

2023-10-18 16:14 UTC, nonorze-VOXX approved these changes
LGTM

2023-10-18 17:36 UTC, merged