Backend insert data  to cart table and search cart by PK ID
PUArallelepiped/PUN-street-Universal-Access pull request #26
Opened 2023-10-18 14:46 UTC by wj461

Just search and insert so no any logic in cart_usecase now

2023-10-18 14:49 UTC, wj461 commented on db/create-customer.sql
> +CREATE TABLE IF NOT EXISTS UserData(
When UserData table pr merge fix it.

2023-10-18 18:02 UTC, nonorze-VOXX requested changes

2023-10-18 18:02 UTC, nonorze-VOXX commented on db/insert-product.sql
> +    ((default), (SELECT store_id from stores LIMIT 1), 'name', 'good food', 10, decode('DEADBEEF', 'hex'), 123,2);
無三不成禮

2023-10-18 18:02 UTC, nonorze-VOXX commented on db/insert-customer.sql
> +    (1, 'asd', 'pwd', 'dsa@gmail.com', '123456', '0912-1123', '2022-10-10 11:30:30', 111);
無三不成禮

2023-10-18 18:02 UTC, nonorze-VOXX commented on backend/api/swagger.yaml
> +
request review @huhuhu0420

2023-10-18 18:02 UTC, nonorze-VOXX commented on backend/cart/delivery/cart_handler.go
> +func sub(s string, n int) string {
request rename

2023-10-18 18:02 UTC, nonorze-VOXX commented on db/insert-product.sql
> +    ((default), (SELECT store_id from stores LIMIT 1), 'name', 'good food', 10, decode('DEADBEEF', 'hex'), 123,2);
(SELECT store_id from stores LIMIT 1) will break something

2023-10-18 18:02 UTC, nonorze-VOXX commented on backend/cart/repository/postgresql.go
> +    ( $1, (SELECT id from UserData LIMIT 1 OFFSET $2), (SELECT product_id from product LIMIT 1 OFFSET $3), (SELECT store_id from stores LIMIT 1 OFFSET $4));
FIX : LIMIT 1 OFFSET $2

2023-10-18 18:02 UTC, nonorze-VOXX commented on backend/cart/repository/postgresql.go
> +	row := p.db.QueryRow("SELECT customer_id, product_id, store_id, product_quantity FROM cart WHERE customer_id = $1 AND product_id = $2 AND store_id = $3", add(cart.CustomerID, 1), add(cart.ProductID,
request sql string to a variable

2023-10-19 02:14 UTC, nonorze-VOXX commented on db/insert-userData.sql
> +    ((default), 'asd', 'pwd', 'avg@gmail.com', '123456', '0912-1123', '2022-10-10 11:30:30', 111);
INSERT INTO no need three times
can the data more diff ?
we will cant see the different of front of user name

2023-10-21 13:21 UTC, wj461 commented on db/insert-product.sql
> +    ((default), (SELECT store_id from stores LIMIT 1), 'name', 'good food', 10, decode('DEADBEEF', 'hex'), 123,2);
fix

2023-10-21 13:27 UTC, nonorze-VOXX commented
docker-compose up no work

2023-10-22 08:57 UTC, nonorze-VOXX approved these changes
LGTM

2023-10-22 12:24 UTC, merged