userrr
PUArallelepiped/PUN-street-Universal-Access pull request #30
Opened 2023-10-23 12:37 UTC by orangeOAO

2023-10-23 13:08 UTC, nonorze-VOXX commented
merge main first

2023-10-23 13:17 UTC, nonorze-VOXX requested changes

2023-10-23 13:17 UTC, nonorze-VOXX commented on backend/user_log/README.md
> +    psql -U postgres -f UserInitializeTable.sql
existed

2023-10-23 13:17 UTC, nonorze-VOXX commented on backend/user_log/UserInitializeTable.sql
> +);
existed
 SQL語法 建議要大寫

2023-10-23 13:17 UTC, nonorze-VOXX commented on backend/user_log/user_log.go
> +func TF(tmp [4]bool) bool {
titan fall?

2023-10-23 13:17 UTC, nonorze-VOXX commented on backend/user_log/user_log.go
> +}
no need

2023-10-23 13:17 UTC, nonorze-VOXX commented on backend/user_log/user_log.go
> +
maybe can it use 2D array?

2023-10-23 13:32 UTC, orangeOAO commented on backend/user_log/user_log.go
> +}
why

2023-10-24 04:45 UTC, nonorze-VOXX commented on backend/user_log/UserInitializeTable.sql
> +);
docker compose will not run this .sql , it's path is wrong
please check

2023-10-24 04:45 UTC, nonorze-VOXX commented on backend/user_log/string/string.go
> +// }
why have this file

2023-10-24 04:48 UTC, orangeOAO commented on backend/user_log/string/string.go
> +// }
寫驗證ing

2023-10-24 04:50 UTC, orangeOAO commented on backend/user_log/UserInitializeTable.sql
> +);
這是測試用的之後會刪掉ouo

2023-10-24 04:51 UTC, nonorze-VOXX commented on backend/user_log/string/string.go
> +// }
你要交在同一個pr？

2023-10-24 04:53 UTC, orangeOAO commented on backend/user_log/string/string.go
> +// }
沒
其實我不知道為啥我後面push的會加到之前pr 的裡面

2023-10-24 04:55 UTC, nonorze-VOXX commented on backend/user_log/string/string.go
> +// }
因為你在同一個branch上做
它的單位是branch 
你應該在要有一條做事 一條pr

2023-10-24 04:57 UTC, orangeOAO commented on backend/user_log/string/string.go
> +// }
歐給歐給 回家改

2023-10-31 05:10 UTC, closed without merging