Upload byte Img to Url
PUArallelepiped/PUN-street-Universal-Access pull request #55
Opened 2023-11-21 16:50 UTC by wj461

when post product
need send byte img for CartIngo.picture

2023-11-25 17:35 UTC, wj461 commented
CartIngo -> CartInfo

2023-11-25 17:38 UTC, nonorze-VOXX requested changes
INWOMM

2023-11-30 11:18 UTC, NOOBDY commented on backend/product/usecase/product_usecase.go
> +	v["format"] = []string{s.Format}
```suggestion
	v := map[string][]string{
	  "key": []string{s.Key},
	  "action": []string{s.Action},
	  "source": []string{s.Source},
	  "format": []string{s.Format},
	}
```

2023-11-30 11:20 UTC, NOOBDY commented on backend/domain/product.go
> +}
```suggestion
type ResponseInfo struct {
	StatusCode int       `json:"status_code"`
	Image      struct {
	  Url       string `json:"url"`
	  UrlViewer string `json:"url_viewer"`
	} `json:"image"`
}
```

2023-12-28 01:35 UTC, closed without merging