Refector api 2
PUArallelepiped/PUN-street-Universal-Access pull request #84
Opened 2023-12-08 08:57 UTC by wj461

in kawaii api
redo-in-refectir-api-2 pr

2023-12-11 07:49 UTC, nonorze-VOXX requested changes
GET```localhost:5000/api/v1/store/2/products```
get
```
    "product_label_array": null,
    "event_discount_array": null
```
can it be a []?

2023-12-11 07:54 UTC, nonorze-VOXX commented
LGTM

2023-12-11 14:00 UTC, huhuhu0420 commented
/store/{storeID}/products
是不是不需要回傳狀態為0的商品

2023-12-11 15:43 UTC, wj461 commented
> GET`localhost:5000/api/v1/store/2/products` get
> 
> ```
>     "product_label_array": null,
>     "event_discount_array": null
> ```
> 
> can it be a []?

fix

2023-12-11 15:43 UTC, wj461 commented
> /store/{storeID}/products 是不是不需要回傳狀態為0的商品

fix

2023-12-12 09:46 UTC, nonorze-VOXX requested changes
localhost:5000/api/v1/store/1/products no work

2023-12-12 12:22 UTC, wj461 commented
> localhost:5000/api/v1/store/1/products no work

fix

2023-12-12 16:31 UTC, huhuhu0420 commented on backend/product/usecase/product_usecase.go
> +			err := pu.productRepo.ChangeProductStatusByProductID(ctx, product.ProductId, product.Status)
執行這個有意義嗎

2023-12-12 18:36 UTC, wj461 commented on backend/product/usecase/product_usecase.go
> +			err := pu.productRepo.ChangeProductStatusByProductID(ctx, product.ProductId, product.Status)
這邊是判斷如果product除了狀態以外都一樣的話就只修改狀態
像是 商店只更改為無庫存
這樣的話就只需要更改狀態 不新增新的商品

2023-12-13 07:01 UTC, huhuhu0420 approved these changes
looks good

2023-12-13 12:06 UTC, nonorze-VOXX approved these changes
LGTM

2023-12-13 12:08 UTC, merged