Shoplist connect backend
PUArallelepiped/PUN-street-Universal-Access pull request #90
Opened 2023-12-15 20:08 UTC by nonorze-VOXX

2023-12-16 12:26 UTC, wj461 commented
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/781d2536-86d7-46e5-9f78-d5895d0fcaae)
tag置左

2023-12-16 12:29 UTC, wj461 reviewed
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/017c80af-46ea-40fa-8b84-807e2b84ade7)
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/2e1cfd39-b0b7-4943-b662-4bacc7dffe8e)
修成第二張圖

2023-12-16 12:30 UTC, wj461 reviewed
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/1dd06fcd-f39c-4cdd-8e6e-de88b4112527)
改顏色
跟新增拖拉時會有當前數字顯示
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/13d22f55-449d-493a-8acc-86e3a44a4ec7)

2023-12-16 12:31 UTC, wj461 reviewed
商品名稱與tag交換位置

2023-12-16 12:33 UTC, wj461 reviewed
shop card hover 灰色再淺一點 大概200或300吧

2023-12-16 12:34 UTC, wj461 reviewed
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/6b90cdaa-b374-4a1e-9393-26fffd4c5aa9)
這一區這一區塊應該換成category樣式
![Uploading 圖片.png…]()

2023-12-17 19:12 UTC, wj461 requested changes

2023-12-17 19:12 UTC, wj461 commented on frontend/src/routes/shops/+page.svelte
> +		<Input type="text" placeholder="QQㄋㄟㄋㄟ好喝到咩噗茶" class="m-5  max-w-xs bg-white" />
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/f3b0a1e3-ee6a-4f45-8338-5fa4193048ec)
修改裡面字形的外觀
跟加放大鏡 icon

2023-12-18 08:19 UTC, wj461 requested changes

2023-12-18 08:19 UTC, wj461 commented on frontend/src/routes/shops/+page.svelte
> +	<div class=" m-4 flex h-min flex-wrap gap-3">
gap-3 可能可以拔掉
![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/7881713f-6262-40fd-87cf-c152ff2289c4)

![圖片](https://github.com/PUArallelepiped/PUN-street-Universal-Access/assets/119517466/2403794f-97e3-4346-860a-c859a2cc7d0b)

2023-12-19 18:43 UTC, nonorze-VOXX commented on frontend/src/routes/shops/+page.svelte
> +	<div class=" m-4 flex h-min flex-wrap gap-3">
fixed

2023-12-20 02:38 UTC, wj461 approved these changes
looks good

2023-12-20 11:30 UTC, huhuhu0420 approved these changes

2023-12-20 11:30 UTC, merged