Post store rate
PUArallelepiped/PUN-street-Universal-Access pull request #96
Opened 2023-12-17 15:30 UTC by orangeOAO

POST /store/{storeID}/rate

2023-12-17 18:04 UTC, wj461 commented on backend/store/delivery/store_handler.go
> +	s.StoreUsecase.CalculateRate(c, storeID, rate)
```suggestion
	err := s.StoreUsecase.CalculateRate(c, storeID, rate)
	if err := nil {
	    logrus.Error(err)
		c.Status(500)
		return
	}
	
	c.Status(200)
```

2023-12-18 06:58 UTC, orangeOAO commented on backend/store/delivery/store_handler.go
> +	s.StoreUsecase.CalculateRate(c, storeID, rate)
fix

2023-12-18 07:44 UTC, wj461 commented
You can look readme format part to auto format

2023-12-18 07:57 UTC, wj461 commented
I think you can merge upsteam

2023-12-19 10:30 UTC, nonorze-VOXX requested changes
擋一下評價分數的範圍

2023-12-20 12:53 UTC, wj461 approved these changes
looks good

2023-12-20 12:58 UTC, nonorze-VOXX approved these changes
LGtm

2023-12-20 12:58 UTC, merged